[build]
  base = "site/"
  publish = "public/"
  command = """
    hugo --gc --minify && \
    CGO_ENABLED=0 go build -o netlify/functions/news netlify/functions/news/news.go && \
    CGO_ENABLED=0 go build -o netlify/functions/browse netlify/functions/browse/browse.go && \
    CGO_ENABLED=0 go build -o netlify/functions/plot netlify/functions/plot/plot.go
  """

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.19.4"
