[build]
base = "site/"
publish = "public/"
command = """
    hugo --gc --minify && cd netlify/functions/ && \
    cd news && go get ./... && CGO_ENABLED=0 go build -o ../news news.go && cd .. && \
    cd browse && go get ./... && CGO_ENABLED=0 go build -o ../browse browse.go && cd .. && \
    cd plot && go get ./... && CGO_ENABLED=0 go build -o ../plot plot.go && cd .. && \
    cd plot_bar && go get ./... && CGO_ENABLED=0 go build -o ../plot_bar plot_bar.go && cd .. && \
    echo 'OK'
  """

[context.production.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.19.4"

[[headers]]
# Apply these headers to a specific API endpoint
for = "/index.json"

[headers.values]
# Set the Cache-Control header
# max-age=600 tells the browser to cache for 600 seconds (10 minutes)
# s-maxage=600 tells Netlify's CDN and other shared caches to cache for 600 seconds (10 minutes)
# public indicates that the response can be stored by any cache
Cache-Control = "public, max-age=600, s-maxage=600"
