[build]
  base = "site/"
  publish = "public/"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[functions]
  # Directory with serverless functions, including background
  # functions, to deploy. This is relative to the base directory
  # if one has been set, or the root directory if
  # a base hasn’t been set.
  directory = "../netlify/functions/"
