[build]
  base = "site/"
  publish = "public/"
  command = """
    hugo --gc --minify && cd netlify/functions/ && \
    cd news && \
    go get ./... && \
    CGO_ENABLED=0 go build -o ../news news.go && \
    cd ../browse && \
    go get ./... && \
    CGO_ENABLED=0 go build -o ../browse browse.go && \
    cd ../plot && \
    go get ./... && \
    CGO_ENABLED=0 go build -o ../plot plot.go\
  """

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.19.4"
