baseURL = "https://yauhen.space/"
languageCode = "en-us"
title = "notes"

theme = "tt-theme"

paginate = 10
pygmentsCodeFences = true
pygmentsStyle = "tango"

enableRobotsTXT = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
